### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by agothan1** [sseemayer/qstat-pretty#1]
Tried to use qstat-pretty but I get the following: 

  File "/usr/bin/pstat", line 71, in <module>
    pretty.pretty_table(jobs)
  File "/usr/lib/python2.6/site-packages/qstatpretty/pretty.py", line 146, in pretty_table
    print(ttytable.pretty_table(tbl, table_format, delimiters=delimiters))
  File "/usr/lib64/python2.6/encodings/iso8859_15.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-156: character maps to <undefined>

Thanks!

**Comment by sseemayer** [comment]
Can you send me a dump of the qstat output by running:

```
qstat -xml > qstat-output.xml
```

Thanks!

**Comment by nagas** [comment]
I have the same issue. Here are details

https://monosnap.com/image/wJwR8uGLR3otDPXOG4V7atgAQiZ709
https://monosnap.com/image/qEYD6aplUQbwCScU4w2pFNKEtOfMrb

qstat output (file was commited, not copy-pasted)
https://gist.github.com/nagas/7fe4d6b338a9551eed45

**Comment by jhermann** [comment]
The problem is very likely not the qstat output, but the table frames. @agothan1 has a 8-byte encoding active, instead of UTF-8. Check your LANG.
