### ISSUE TITLE
Missing LICENSE, and plans?

### ISSUE THREAD

**Issue by jhermann** [sseemayer/qstat-pretty#3]
Hi, I like your table code a lot, any plans to release it separately? If not, mind if I do?

Also, your code is not licensed in any way – in that way it's published, but not Open Source, since nobody can (re-)use it. Mind to provide a license?

**Comment by sseemayer** [comment]
Sorry about the late reply - You're more than welcome to use the table code, maybe also have a look at #4 which provides some more cool table-related things  - we could also use a separate table package created by you within qstat-pretty. 

I've also added an MIT license.
