### ISSUE TITLE
AttributeError: __exit__

### ISSUE THREAD

**Issue by vladimir-kozyrev** [sseemayer/qstat-pretty#7]
Hi, I'd appreciate any suggestion about what's going on.
Python version: 2.7.6
I'm using default qstat-pretty.conf (copy of qstat-pretty.conf.example)
Grid Engine

``` python
$ pstat
Traceback (most recent call last):
  File "/path/to/qstat-pretty/pstat", line 139, in <module>
    main()
  File "/path/to/qstat-pretty/pstat", line 112, in main
    jobs = parser.parse(source(parser, args))
  File "/path/to/qstat-pretty/qstatpretty/source.py", line 21, in get
    with subprocess.Popen(commandline, stdout=subprocess.PIPE) as proc:
AttributeError: __exit__
```

I've defined **parse_args()** function in the interpreter, then tried to assign **opt = parse_args()**.
Turns out, that **opt** variable is of _NoneType_.

**Comment by sseemayer** [comment]
I'm not sure what you're trying to do, did you modify the source code 
somehow? If so, can I see some code? If not, your config file? If you're 
not comfortable posting them publicly, you can email me at stefan@seemayer.de

The error message you're showing indicates some problem in using the Popen 
object in a context manager. I'm not sure if this is a problem with your 
python version but will run some tests.

Am 14. Dezember 2015 2:23:25 nachm. schrieb fieryvova 
notifications@github.com:

**Comment by vladimir-kozyrev** [comment]
Hi @sseemayer, thanks for a prompt reply.
I haven't modified the source code, nor configuration file.
I cloned the master branch of your project over HTTPS and changed nothing.
I've just tried to execute **pstat** using Python 2.6.6

``` python
/path/to/qstatpretty/config.py:13: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
  parser = configparser.SafeConfigParser()
Traceback (most recent call last):
  File "./pstat", line 139, in <module>
    main()
  File "./pstat", line 112, in main
    jobs = parser.parse(source(parser, args))
  File "/path/to/qstatpretty/source.py", line 21, in get
    with subprocess.Popen(commandline, stdout=subprocess.PIPE) as proc:
AttributeError: 'Popen' object has no attribute '__exit__'
```

There's no X server running on a server that I'm using to run **pstat**. Can it be the reason of the failure?

**Comment by sseemayer** [comment]
I've had a look now and this error is due to the [subprocess module only supporting context managers since Python 3.2](https://stackoverflow.com/questions/30421003/exception-handling-when-using-pythons-subprocess-popen). It should probably not be a big deal to make this backwards-compatible by manually closing the streams although I'm not sure if I'll manage to do this before christmas / the new year. If you're in a hurry, you might consider upgrading your Python to a version that isn't more than 5 years old :wink:

**Comment by sseemayer** [comment]
OK, it turned out to be very easy - hope this helps!

**Comment by vladimir-kozyrev** [comment]
Thanks for fixing it so fast! Could you do the same for **source_local** function?
You've changed only **source_ssh**.

**Comment by vladimir-kozyrev** [comment]
Thanks a lot!
