### ISSUE TITLE
0 jobs total

### ISSUE THREAD

**Issue by vladimir-kozyrev** [sseemayer/qstat-pretty#8]
Hi,
After a recent fix https://github.com/sseemayer/qstat-pretty/commit/8d2f6e86017e2425c083e2e591268fedb29ac095, **pstat** is now working with python/2.7.6
There's a strange behaviour, though.
When I execute **qstat** command, I see a list of user's jobs.
When I execute **pstat**, I get _0 jobs total_ message.
Thanks for looking into this!

**Comment by sseemayer** [comment]
Can you please provide me an output of the `qstat -xml` command so I can debug? (either a gist or per e-mail to stefan@seemayer.de would work)

**Comment by vladimir-kozyrev** [comment]
Sure, here it comes.

``` xml
<?xml version='1.0'?>
<job_info  xmlns:xsd="https://github.com/gridengine/gridengine/raw/master/source/dist/util/resources/schemas/qstat/qstat.xsd">
  <queue_info>
    <job_list state="running">
      <JB_job_number>179556</JB_job_number>
      <JAT_prio>0.50500</JAT_prio>
      <JB_name>random_array</JB_name>
      <JB_owner>username</JB_owner>
      <state>r</state>
      <JAT_start_time>2015-12-15T06:12:03</JAT_start_time>
      <queue_name>all.q@example.com</queue_name>
      <jclass_name></jclass_name>
      <slots>1</slots>
      <tasks>35236337</tasks>
    </job_list>
    <job_list state="running">
      <JB_job_number>179556</JB_job_number>
      <JAT_prio>0.50500</JAT_prio>
      <JB_name>random_array</JB_name>
      <JB_owner>username</JB_owner>
      <state>r</state>
      <JAT_start_time>2015-12-15T06:12:03</JAT_start_time>
      <queue_name>all.q@example.com</queue_name>
      <jclass_name></jclass_name>
      <slots>1</slots>
      <tasks>35236339</tasks>
    </job_list>
  </queue_info>
</job_info>
```

**Comment by sseemayer** [comment]
Your XML files seem to have a little different structure than the ones that I've seen before (maybe a different GridEngine version?) - could you try if the above commit fixes things? I was able to show the table using `pstat --source-file yourfile.xml --flavor gridengine`

**Comment by vladimir-kozyrev** [comment]
No, that doesn't fix the issue.
In the company I work for, we use [Univa Grid Engine](http://www.univa.com/products/). If it's impossible (too hard) to make it work for that version of GridEngine - it's okay with me.

**Comment by vladimir-kozyrev** [comment]
I tried to execute the command above.

``` python
$ qstat-pretty/pstat --source-file yourfile.xml --flavor gridengine
Traceback (most recent call last):
  File "qstat-pretty/pstat", line 139, in <module>
    main()
  File "qstat-pretty/pstat", line 112, in main
    jobs = parser.parse(source(parser, args))
  File "/path/to/qstat-pretty/qstatpretty/source.py", line 12, in get
    return StringIO(f.read())
TypeError: initial_value must be unicode or None, not str
```

**Comment by sseemayer** [comment]
Bleh, encoding problems with Python2 :-) Could you try again with these changes?

**Comment by vladimir-kozyrev** [comment]
Thanks a lot for your effort! It's working perfectly now.
